import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import "./globals.css";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-nunito",
  display: "swap",
});

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: ReactNode;
  modal: ReactNode;
}>) {
  return (
    <TanStackProvider>
      <html lang="en">
        <body className={nunito.variable}>
          <Header />
          {children}
          {modal}
          <Footer />
        </body>
      </html>
    </TanStackProvider>
  );
}
